// Serverless site-guide chatbot for ramphal.design.
//
// Replaces the n8n webhook. The Vue widget (src/components/CustomChatUI.vue)
// POSTs { chatInput, sessionId, metadata } here; this returns { output }.
// Claude is given the site's public writing/work as a prompt-cached system
// block (see ../_context.json, generated by scripts/build-chat-context.mjs).
//
// Runtime: Vercel Node serverless function. Requires env ANTHROPIC_API_KEY.
// Optional env:
//   CHAT_MODEL        model id (default claude-haiku-4-5)
//   ALLOWED_ORIGINS   comma-separated origin allowlist for CORS
//   MAX_INPUT_CHARS   reject longer messages (default 2000)

const Anthropic = require('@anthropic-ai/sdk');
const context = require('../_context.json');

const DEFAULT_ORIGINS = [
  'https://ramphal.design',
  'https://www.ramphal.design',
  'https://jacquesramphal.github.io',
  'http://localhost:8080',
  'http://localhost:3000',
];

const ALLOWED_ORIGINS = (
  process.env.ALLOWED_ORIGINS
    ? process.env.ALLOWED_ORIGINS.split(',').map((s) => s.trim())
    : DEFAULT_ORIGINS
).filter(Boolean);

const MODEL = process.env.CHAT_MODEL || 'claude-haiku-4-5';
const MAX_INPUT_CHARS = Number(process.env.MAX_INPUT_CHARS || 2000);

const PERSONA = [
  "You are the site guide for ramphal.design, the personal site of Jacques Ramphal, a design engineer.",
  "Your job is to help visitors find and understand Jacques's projects, case studies, writing, and background.",
  "",
  "Rules:",
  "- Answer only from the SITE CONTENT provided below. If something isn't covered, say you don't have that on the site and point the visitor to the closest relevant work or article, or suggest they reach out via the contact link.",
  "- Never invent projects, articles, dates, employers, or facts. Do not speculate.",
  "- Be concise and direct. A few sentences is usually enough. When you reference a piece, include its link (e.g. /doc/...) so the visitor can read it.",
  "- Refer to Jacques in the third person. You are a guide, not Jacques himself.",
  "- If asked about anything unrelated to Jacques or this site, gently redirect to what the site covers.",
].join('\n');

function applyCors(req, res) {
  const origin = req.headers.origin;
  if (origin && ALLOWED_ORIGINS.includes(origin)) {
    res.setHeader('Access-Control-Allow-Origin', origin);
    res.setHeader('Vary', 'Origin');
  }
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Accept');
  res.setHeader('Access-Control-Max-Age', '86400');
}

module.exports = async function handler(req, res) {
  applyCors(req, res);

  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }
  if (req.method !== 'POST') {
    res.status(405).json({ output: 'Method not allowed.' });
    return;
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('ANTHROPIC_API_KEY is not set');
    res.status(500).json({ output: 'The chat is not configured yet. Please try again later.' });
    return;
  }

  let body = req.body;
  if (typeof body === 'string') {
    try {
      body = JSON.parse(body);
    } catch (_) {
      body = {};
    }
  }
  body = body || {};

  const message = String(body.chatInput || body.message || body.text || '').trim();
  if (!message) {
    res.status(400).json({ output: 'Please type a question.' });
    return;
  }
  if (message.length > MAX_INPUT_CHARS) {
    res.status(413).json({ output: `Please keep your message under ${MAX_INPUT_CHARS} characters.` });
    return;
  }

  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

  try {
    const response = await client.messages.create({
      model: MODEL,
      max_tokens: 1024,
      system: [
        { type: 'text', text: PERSONA },
        {
          type: 'text',
          text: 'SITE CONTENT (the only source of truth):\n\n' + context.content,
          cache_control: { type: 'ephemeral' },
        },
      ],
      messages: [{ role: 'user', content: message }],
    });

    const output = response.content
      .filter((b) => b.type === 'text')
      .map((b) => b.text)
      .join('')
      .trim();

    res.status(200).json({ output: output || "Sorry, I couldn't come up with an answer for that." });
  } catch (err) {
    console.error('Chat error:', err && err.message ? err.message : err);
    const status = err && err.status === 429 ? 429 : 502;
    res.status(status).json({
      output:
        status === 429
          ? "I'm getting a lot of questions right now — please try again in a moment."
          : 'Something went wrong reaching the assistant. Please try again.',
    });
  }
};
