// Serverless site-guide chatbot for ramphal.design.
//
// Replaces the n8n webhook. The Vue widget (src/components/CustomChatUI.vue)
// POSTs { chatInput, sessionId, metadata } here; this returns { output }.
// Claude is given the site's public writing/work as a prompt-cached system
// block (see ./_context.json, generated by scripts/build-chat-context.mjs).
//
// DEPENDENCY-FREE BY DESIGN: this repo is a pnpm workspace, and Vercel's
// install doesn't reliably populate chat-api/node_modules. So we call the
// Anthropic Messages API and Upstash KV REST API directly with global fetch
// (built into Node 18+ on Vercel) — no npm packages to install or bundle.
//
// Runtime: Vercel Node serverless function. Requires env ANTHROPIC_API_KEY.
// Optional env:
//   CHAT_MODEL        model id (default claude-haiku-4-5)
//   ALLOWED_ORIGINS   comma-separated origin allowlist for CORS
//   MAX_INPUT_CHARS   reject longer messages (default 2000)
//   SESSION_TTL_SECONDS   history expiry (default 86400 = 24h)
//   KV_REST_API_URL / KV_REST_API_TOKEN         (injected by Vercel KV)
//   UPSTASH_REDIS_REST_URL / UPSTASH_REDIS_REST_TOKEN  (Upstash naming)

const context = require('./_context.json'); // colocated JSON — no npm dep, always bundled

const ANTHROPIC_URL = 'https://api.anthropic.com/v1/messages';

const DEFAULT_ORIGINS = [
  'https://ramphal.design',
  'https://www.ramphal.design',
  'https://jacquesramphal.github.io',
  'http://localhost:8080',
  'http://localhost:3000',
];

const ALLOWED_ORIGINS = (
  process.env.ALLOWED_ORIGINS
    ? process.env.ALLOWED_ORIGINS.split(',').map((s) => s.trim())
    : DEFAULT_ORIGINS
).filter(Boolean);

const MODEL = process.env.CHAT_MODEL || 'claude-haiku-4-5';
const MAX_INPUT_CHARS = Number(process.env.MAX_INPUT_CHARS || 2000);
const SESSION_TTL_SECONDS = Number(process.env.SESSION_TTL_SECONDS || 86400);
const MAX_HISTORY_MESSAGES = 12; // cap stored messages to bound token cost

const KV_URL = process.env.KV_REST_API_URL || process.env.UPSTASH_REDIS_REST_URL;
const KV_TOKEN = process.env.KV_REST_API_TOKEN || process.env.UPSTASH_REDIS_REST_TOKEN;

const PERSONA = [
  "You are the site guide for ramphal.design, the personal site of Jacques Ramphal, a design engineer who works where design systems, code, and AI meet. You help visitors find and understand his projects, case studies, writing, and background.",
  "",
  "WHAT YOU KNOW",
  "- Answer only from the SITE CONTENT below. Never invent projects, articles, dates, employers, links, or facts, and never guess. If something isn't covered, say so plainly and point to the nearest relevant work or writing.",
  "- When you reference a piece, link it using its exact Link value from SITE CONTENT (e.g. /doc/friction). Never fabricate a URL.",
  "- Speak about Jacques in the third person. You are a guide, not Jacques. If asked something off-topic, briefly redirect to what the site covers.",
  "",
  "HOW YOU WRITE — match the restraint and specificity of Jacques's own writing:",
  "- Lead with the specific thing, not a label. 'Genie coordinates AI agents to take over routine delivery work' beats 'Genie is an innovative platform'.",
  "- Be brief. Two or three sentences usually answers the question. Trust the reader; don't over-explain.",
  "- Plain, direct sentences. No marketing adjectives (seamless, robust, comprehensive, intuitive, cutting-edge, best-in-class), no filler adverbs (moreover, notably, indeed, furthermore), no reach-verbs (delve, leverage, unpack, underscore).",
  "- Avoid AI tells: no 'it's not X, it's Y' pivot sentences, no 'that's the point' meta-verdicts, no symmetrical two-part closers, no three-item adjective clusters.",
  "- Use em dashes sparingly. Prefer a comma, or two shorter sentences.",
  "- Don't perform enthusiasm or pitch. Say what the work is and why it mattered, then stop.",
  "",
  "EXAMPLES (for voice and shape, not content to reuse verbatim):",
  "Q: What does he write about?",
  "A: Things at the edges of design practice. In /doc/friction, for instance, he argues that friction only sharpens you when there's something steady to push against, drawn from pulling a falling-apart project's design into a single source of truth. Tell me a topic and I'll point you to the closest piece.",
  "",
  "Q: Does he actually write code?",
  "A: Yes. He builds components in React and Vue, prototypes interactions in code when Figma runs out of road, and pairs with engineers on architecture. Coding keeps him honest about what's buildable.",
].join('\n');

function applyCors(req, res) {
  const origin = req.headers.origin;
  if (origin && ALLOWED_ORIGINS.includes(origin)) {
    res.setHeader('Access-Control-Allow-Origin', origin);
    res.setHeader('Vary', 'Origin');
  }
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Accept');
  res.setHeader('Access-Control-Max-Age', '86400');
}

// Client-supplied; sanitize before using as a storage key. Empty => no persistence.
function sessionKey(sessionId) {
  const safe = String(sessionId || '').replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 64);
  return safe ? `chat:v1:${safe}` : null;
}

// Upstash Redis REST: POST the command as a JSON array, get back { result }.
async function kvCommand(args) {
  const resp = await fetch(KV_URL, {
    method: 'POST',
    headers: { Authorization: `Bearer ${KV_TOKEN}`, 'content-type': 'application/json' },
    body: JSON.stringify(args),
  });
  if (!resp.ok) throw new Error(`KV ${args[0]} -> ${resp.status}`);
  return (await resp.json()).result;
}

async function loadHistory(key) {
  if (!KV_URL || !KV_TOKEN || !key) return [];
  try {
    const result = await kvCommand(['GET', key]);
    if (!result) return [];
    const parsed = JSON.parse(result);
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    console.error('KV read failed:', err && err.message ? err.message : err);
    return [];
  }
}

async function saveHistory(key, messages) {
  if (!KV_URL || !KV_TOKEN || !key) return;
  try {
    const trimmed = messages.slice(-MAX_HISTORY_MESSAGES);
    await kvCommand(['SET', key, JSON.stringify(trimmed), 'EX', String(SESSION_TTL_SECONDS)]);
  } catch (err) {
    console.error('KV write failed:', err && err.message ? err.message : err);
  }
}

module.exports = async function handler(req, res) {
  applyCors(req, res);

  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }
  if (req.method !== 'POST') {
    res.status(405).json({ output: 'Method not allowed.' });
    return;
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('ANTHROPIC_API_KEY is not set');
    res.status(500).json({ output: 'The chat is not configured yet. Please try again later.' });
    return;
  }

  let body = req.body;
  if (typeof body === 'string') {
    try {
      body = JSON.parse(body);
    } catch (_) {
      body = {};
    }
  }
  body = body || {};

  const message = String(body.chatInput || body.message || body.text || '').trim();
  if (!message) {
    res.status(400).json({ output: 'Please type a question.' });
    return;
  }
  if (message.length > MAX_INPUT_CHARS) {
    res.status(413).json({ output: `Please keep your message under ${MAX_INPUT_CHARS} characters.` });
    return;
  }

  try {
    const key = sessionKey(body.sessionId);
    const history = await loadHistory(key);
    const outgoing = [...history, { role: 'user', content: message }];

    const apiRes = await fetch(ANTHROPIC_URL, {
      method: 'POST',
      headers: {
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 1024,
        system: [
          { type: 'text', text: PERSONA },
          {
            type: 'text',
            text: 'SITE CONTENT (the only source of truth):\n\n' + context.content,
            cache_control: { type: 'ephemeral' },
          },
        ],
        messages: outgoing,
      }),
    });

    if (!apiRes.ok) {
      const detail = await apiRes.text();
      console.error('Anthropic API error', apiRes.status, detail);
      const status = apiRes.status === 429 ? 429 : 502;
      res.status(status).json({
        output:
          status === 429
            ? "I'm getting a lot of questions right now — please try again in a moment."
            : 'Something went wrong reaching the assistant. Please try again.',
      });
      return;
    }

    const data = await apiRes.json();
    const output = (data.content || [])
      .filter((b) => b.type === 'text')
      .map((b) => b.text)
      .join('')
      .trim();

    const answer = output || "Sorry, I couldn't come up with an answer for that.";
    await saveHistory(key, [...outgoing, { role: 'assistant', content: answer }]);

    res.status(200).json({ output: answer });
  } catch (err) {
    console.error('Chat error:', err && err.stack ? err.stack : err);
    res.status(502).json({ output: 'Something went wrong reaching the assistant. Please try again.' });
  }
};
